-- ============================================================================
-- DormCRU — insert-dorms.sql
-- รายชื่อหอพักเครือข่ายทางการ 61 หอ ของมหาวิทยาลัยราชภัฏเชียงราย
-- แหล่งข้อมูล: สำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มร.ชร.
--              https://aso.crru.ac.th/asoblog/dormnetwork
--
-- หมายเหตุ: เว็บต้นทางมีเฉพาะชื่อหอ/ประเภท/ลิงก์ Facebook เท่านั้น
-- ราคา ห้องว่าง ระยะทางจากประตู จึงเว้นเป็น null (ยังไม่ระบุ) ให้เจ้าของหอมากรอกเอง
--
-- วิธีใช้: Supabase -> SQL Editor -> วางทั้งไฟล์ -> Run
-- (ถ้าเคยโหลดข้อมูลชุดเก่าไว้แล้ว ให้ลบก่อนด้วย: delete from dorms where verified = false;)
-- ============================================================================

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('ทริปเปิลพี', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/1034584/pexels-photo-1034584.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/7055757/pexels-photo-7055757.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619255/pexels-photo-33619255.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/profile.php?id=100009134251032', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('ภูชมดาว', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/2416932/pexels-photo-2416932.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/15792555/pexels-photo-15792555.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/19390169/pexels-photo-19390169.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/profile.php?id=100012000224471', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('PPSP', 'หอชายล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/2416933/pexels-photo-2416933.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/8251695/pexels-photo-8251695.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/14121007/pexels-photo-14121007.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('ธนณัฐ', 'หอชายล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/8251681/pexels-photo-8251681.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5858236/pexels-photo-5858236.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619257/pexels-photo-33619257.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/profile.php?id=100006856248956', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('อภิสรา', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619255/pexels-photo-33619255.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/1455613048023448/', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('เงินยวง', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/7055757/pexels-photo-7055757.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/6782344/pexels-photo-6782344.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/19390169/pexels-photo-19390169.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/profile.php?id=100024388698688', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('ไทเสรีปาร์ค', 'หอชายล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/15792555/pexels-photo-15792555.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5858228/pexels-photo-5858228.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/14121007/pexels-photo-14121007.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/pages/251804134878673', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('บ้านน้ำอุ่น', 'หอชายล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/8251695/pexels-photo-8251695.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5858234/pexels-photo-5858234.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619257/pexels-photo-33619257.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('ชยานีคอร์ท', 'หอชายล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/5858236/pexels-photo-5858236.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/1034584/pexels-photo-1034584.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619255/pexels-photo-33619255.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/chayaneecourt', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('เทียมจันทร์', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/2416932/pexels-photo-2416932.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/19390169/pexels-photo-19390169.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/599661180135782/', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('จ่าพันธ์ศักดิ์ 2', 'หอชายล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/6782344/pexels-photo-6782344.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/2416933/pexels-photo-2416933.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/14121007/pexels-photo-14121007.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('แอลเอ', 'หอชายล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/5858228/pexels-photo-5858228.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/8251681/pexels-photo-8251681.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619257/pexels-photo-33619257.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/ppech.la', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('น้ำอินทร์', 'หอชายล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/5858234/pexels-photo-5858234.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619255/pexels-photo-33619255.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/pages/420211831355174', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('อรวรรณ', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/1034584/pexels-photo-1034584.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/7055757/pexels-photo-7055757.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/19390169/pexels-photo-19390169.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/ratana.rakpanale', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('แฮปปี้โฮมคอร์ท', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/2416932/pexels-photo-2416932.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/15792555/pexels-photo-15792555.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/14121007/pexels-photo-14121007.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/profile.php?id=100004807893321', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('รักษา', 'หอชายล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/2416933/pexels-photo-2416933.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/8251695/pexels-photo-8251695.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619257/pexels-photo-33619257.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/profile.php?id=100016663201133', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('ภัทรวดี', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/8251681/pexels-photo-8251681.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5858236/pexels-photo-5858236.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619255/pexels-photo-33619255.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/profile.php?id=100004715538790', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('ณิชชาพัชร์', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/19390169/pexels-photo-19390169.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('ศุภาพร', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/7055757/pexels-photo-7055757.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/6782344/pexels-photo-6782344.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/14121007/pexels-photo-14121007.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('สุดารัตน์', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/15792555/pexels-photo-15792555.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5858228/pexels-photo-5858228.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619257/pexels-photo-33619257.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/profile.php?id=100012848528545', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('รัตนาวดี 1', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/8251695/pexels-photo-8251695.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5858234/pexels-photo-5858234.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619255/pexels-photo-33619255.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/rattanavadee2/', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('รัตนาวดี 2', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/5858236/pexels-photo-5858236.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/1034584/pexels-photo-1034584.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/19390169/pexels-photo-19390169.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('สองปั้น', 'หอชายล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/2416932/pexels-photo-2416932.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/14121007/pexels-photo-14121007.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/1481698028712243/', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('วัฒนา', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/6782344/pexels-photo-6782344.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/2416933/pexels-photo-2416933.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619257/pexels-photo-33619257.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('วัฒนา 2', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/5858228/pexels-photo-5858228.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/8251681/pexels-photo-8251681.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619255/pexels-photo-33619255.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('บ้านฝ้าย', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/5858234/pexels-photo-5858234.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/19390169/pexels-photo-19390169.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/profile.php?id=100009741480531', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('บ้านแสนสบาย', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/1034584/pexels-photo-1034584.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/7055757/pexels-photo-7055757.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/14121007/pexels-photo-14121007.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('พลอยชมภู', 'หอชายล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/2416932/pexels-photo-2416932.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/15792555/pexels-photo-15792555.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619257/pexels-photo-33619257.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/ploy.chompoo.313', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('บุษราคัม', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/2416933/pexels-photo-2416933.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/8251695/pexels-photo-8251695.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619255/pexels-photo-33619255.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('บุษราคัม 2', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/8251681/pexels-photo-8251681.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5858236/pexels-photo-5858236.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/19390169/pexels-photo-19390169.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('อภิญษยา 1', 'หอชายล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/14121007/pexels-photo-14121007.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/profile.php?id=100092527032637', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('อภิญษยา 2', 'หอชายล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/7055757/pexels-photo-7055757.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/6782344/pexels-photo-6782344.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619257/pexels-photo-33619257.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/profile.php?id=100092527032637', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('ศุภญา', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/15792555/pexels-photo-15792555.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5858228/pexels-photo-5858228.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619255/pexels-photo-33619255.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/supaya240/', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('บ้าน 235', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/8251695/pexels-photo-8251695.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5858234/pexels-photo-5858234.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/19390169/pexels-photo-19390169.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('สตรีศรีวรรณ', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/5858236/pexels-photo-5858236.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/1034584/pexels-photo-1034584.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/14121007/pexels-photo-14121007.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('สุขสถิตย์', 'หอชายล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/2416932/pexels-photo-2416932.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619257/pexels-photo-33619257.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('จตุพร', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/6782344/pexels-photo-6782344.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/2416933/pexels-photo-2416933.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619255/pexels-photo-33619255.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('ทิพากร', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/5858228/pexels-photo-5858228.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/8251681/pexels-photo-8251681.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/19390169/pexels-photo-19390169.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('พีเจเพลส', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/5858234/pexels-photo-5858234.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/14121007/pexels-photo-14121007.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('แก้วตา', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/1034584/pexels-photo-1034584.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/7055757/pexels-photo-7055757.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619257/pexels-photo-33619257.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/profile.php?id=100006143896462', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('เพชรพลอย', 'หอชายล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/2416932/pexels-photo-2416932.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/15792555/pexels-photo-15792555.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619255/pexels-photo-33619255.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, 'https://www.facebook.com/160190551305126/', false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('สตรีวันทนีย์', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/2416933/pexels-photo-2416933.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/8251695/pexels-photo-8251695.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/19390169/pexels-photo-19390169.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('นิลักษณ์', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/8251681/pexels-photo-8251681.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5858236/pexels-photo-5858236.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/14121007/pexels-photo-14121007.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('บ้านสวนนภา', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619257/pexels-photo-33619257.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('อัจจุดา', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/7055757/pexels-photo-7055757.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/6782344/pexels-photo-6782344.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619255/pexels-photo-33619255.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('สมพร', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/15792555/pexels-photo-15792555.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5858228/pexels-photo-5858228.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/19390169/pexels-photo-19390169.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('วิจักขณาภรณ์ 2', 'หอชายล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/8251695/pexels-photo-8251695.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5858234/pexels-photo-5858234.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/14121007/pexels-photo-14121007.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('พชรวรรณ', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/5858236/pexels-photo-5858236.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/1034584/pexels-photo-1034584.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619257/pexels-photo-33619257.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('ยามาโตะ', 'หอชายล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/2416932/pexels-photo-2416932.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619255/pexels-photo-33619255.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('เจริญรัตน์ 3', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/6782344/pexels-photo-6782344.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/2416933/pexels-photo-2416933.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/19390169/pexels-photo-19390169.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('พิศมัย', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/5858228/pexels-photo-5858228.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/8251681/pexels-photo-8251681.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/14121007/pexels-photo-14121007.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('มณีจันทร์สุข', 'หอชายล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/5858234/pexels-photo-5858234.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619257/pexels-photo-33619257.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('อารีรัตน์', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/1034584/pexels-photo-1034584.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/7055757/pexels-photo-7055757.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619255/pexels-photo-33619255.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักเครือข่ายที่ขึ้นทะเบียนกับสำนักงานบริการที่พักอาศัย กองพัฒนานักศึกษา มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ราคา ห้องว่าง ระยะทาง และเบอร์ติดต่อ รอเจ้าของหอเข้ามากรอกข้อมูล', null, null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('UniHouse-Single', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/2416932/pexels-photo-2416932.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/15792555/pexels-photo-15792555.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/19390169/pexels-photo-19390169.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักบุคลากร มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ติดต่อสำนักงานบริการที่พักอาศัย โทร. 0-5377-6273', '053-776273', null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('UniHouse-Family', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/2416933/pexels-photo-2416933.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/8251695/pexels-photo-8251695.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/14121007/pexels-photo-14121007.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักบุคลากร มหาวิทยาลัยราชภัฏเชียงราย (สถานะ: ให้บริการ) — ติดต่อสำนักงานบริการที่พักอาศัย โทร. 0-5377-6273', '053-776273', null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('Uni-dorm 1', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/8251681/pexels-photo-8251681.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5858236/pexels-photo-5858236.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619257/pexels-photo-33619257.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักในมหาวิทยาลัยราชภัฏเชียงราย (Uni-dorm) — จองผ่านระบบหอพักนักศึกษาที่ https://otim.crru.ac.th/unidorm หรือติดต่อ โทร. 0-5377-6273', '053-776273', null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('Uni-dorm 2', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619255/pexels-photo-33619255.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักในมหาวิทยาลัยราชภัฏเชียงราย (Uni-dorm) — จองผ่านระบบหอพักนักศึกษาที่ https://otim.crru.ac.th/unidorm หรือติดต่อ โทร. 0-5377-6273', '053-776273', null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('Uni-dorm 3', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/7055757/pexels-photo-7055757.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/6782344/pexels-photo-6782344.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/19390169/pexels-photo-19390169.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักในมหาวิทยาลัยราชภัฏเชียงราย (Uni-dorm) — จองผ่านระบบหอพักนักศึกษาที่ https://otim.crru.ac.th/unidorm หรือติดต่อ โทร. 0-5377-6273', '053-776273', null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('Uni-dorm 4', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/15792555/pexels-photo-15792555.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5858228/pexels-photo-5858228.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/14121007/pexels-photo-14121007.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักในมหาวิทยาลัยราชภัฏเชียงราย (Uni-dorm) — จองผ่านระบบหอพักนักศึกษาที่ https://otim.crru.ac.th/unidorm หรือติดต่อ โทร. 0-5377-6273', '053-776273', null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('Uni-dorm 5', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/8251695/pexels-photo-8251695.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/5858234/pexels-photo-5858234.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619257/pexels-photo-33619257.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักในมหาวิทยาลัยราชภัฏเชียงราย (Uni-dorm) — จองผ่านระบบหอพักนักศึกษาที่ https://otim.crru.ac.th/unidorm หรือติดต่อ โทร. 0-5377-6273', '053-776273', null, false);

insert into dorms (name, hall_type, gate1, gate2, gate3, lat, lng, facilities, rooms, images, description, phone, facebook, verified)
values ('Uni-dorm 6', 'หอหญิงล้วน', null, null, null, null, null, '{}', '[]'::jsonb, array['https://images.pexels.com/photos/5858236/pexels-photo-5858236.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/1034584/pexels-photo-1034584.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/33619255/pexels-photo-33619255.jpeg?auto=compress&cs=tinysrgb&w=900'], 'หอพักในมหาวิทยาลัยราชภัฏเชียงราย (Uni-dorm) — จองผ่านระบบหอพักนักศึกษาที่ https://otim.crru.ac.th/unidorm หรือติดต่อ โทร. 0-5377-6273', '053-776273', null, false);
